### ISSUE TITLE
Safari (OS X) Compatibility

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Website#21]
Bug Name: Safari (OS X) Compatibility
Bug Page/Url: Any legiondark.com page
Bug Information: The new site does not render in Safari (OS X) v8.08. All that comes up is a blank page. The HTML, etc. is there when I view the page source code.  
**Steps To Reproduce The Bug**: Try to load any page under www.legiondark.com using Safari. 

![screen shot 2016-03-04 at 10 38 53 am](https://cloud.githubusercontent.com/assets/17556762/13536549/591b5a9a-e1f5-11e5-935f-ad4ea8b58057.png)

**Comment by atom0s** [comment]
Do you have JavaScript disabled? If so that would be a problem. Outside of that not sure. I don't touch anything made by Apple.

**Comment by Midgardsormr** [comment]
Hi there-

I do not have Javascript disabled. 

This is not an "Apple vs. non-Apple" issue. The code just isn't standards-compliant. There are several errors in the CSS and JS... that's all. 

Note: The site does render properly on the iOS version of Safari... minus the "div" on the right side, which I'm assuming is intentional.

**Comment by atom0s** [comment]
The site validates fine. It makes use of AngularJS which if you run the base site through a validator, yes it is going to fail. Validators do not take custom directives into consideration so they are considered invalid no matter what. (Regardless if they are valid and working.)

If Safari does not support AngularJS there is nothing I can do since I am not going to go out of my way to ensure it works for Apple products. 

I recommend you switch browsers if Safari can't handle new web technology / frameworks. Especially ones made by companies like Google. _(Angular is made by Google.)_

**Comment by atom0s** [comment]
Alright so I installed OSX 10.10 into a VM (ya.. that was a lot of fun), and checked things out. 

Safari does not handle ES6 JavaScript standards properly. There is nothing wrong with the code, it is that Safari itself has issues interpreting it properly. The problem it has is on this line:

```
return `${h}:${m}:${s} (hh:mm:ss)`;
```

This, in ES6, is known as a template string. Safari does not handle the and refuses to work because of it. When the Angular module fails to load any part, it will cause the whole controller to fail and since the site is making use of ng-cloak, you get a white page. 

According to Apple, this is corrected in Safari 9, so if you are not on the latest, try upgrading to Safari 9 or later.

You can find more about ES6 compatiblity here:
https://kangax.github.io/compat-table/es6/

**Comment by atom0s** [comment]
Marking this as closed/wont fix as it is not an issue with the code. Safari just needs to be running the latest version(s) to work with ES6 standards.

**Comment by Midgardsormr** [comment]
FYI, it looks like something fixed this. Site renders under Safari 8 as well now.
