### ISSUE TITLE
Method to "bump" front page news posts-

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Website#37]
**Feature Name**: NewsBump
**Feature Information**: need a way to force a new post back to the top on site index page (not in forum)
**Feature Page/Url**: index page's news widget
**Additional Information**:
I could delete and repost, but that is annoying, especially if the post has attachments.

**Comment by atom0s** [comment]
The site just pulls news posts from the forum with no specialized method of organizing them or treating any as special. Your best bet would be to go in and edit the date of the post you want to bump back up to the top.

**Comment by TeoTwawki** [comment]
Tried that, it updated on forum but on news page stayed right where it was.

**Comment by atom0s** [comment]
The site caches the news for a set time so it wont correct itself until the cache is expired.

**Comment by TeoTwawki** [comment]
I had force refreshed the cache per your instructions on the forum. The news stayed in the same order.

**Comment by atom0s** [comment]
Given that this pulls from phpBB it would require a plugin in phpBB itself to enforce the order. The site itself does not do anything special to pull the news. Instead, the proxy script installed to the forum system handles it. 

An extension for phpBB such as this may suffice:
https://www.phpbb.com/customise/db/extension/change_post_time/

But since this is not something I plan to add into arcanus since it is not really something coded in arcanus, I am going to close this.
