### ISSUE TITLE
Drop percentage of Stone of Balance

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Website#40]
When doing a lookup using either the Item took (to find the mobs that drop this item) or using the Monster Tool (to find that Sobek is one of the mobs that drop it), the search result lists the drop percentage of Stone of Balace off Sobek at a percentage of 176.00%.

Unless percentage rates have changed, no item should exceed a drop percentage of 100.00%, correct?

Please look into this drop percentage and advise/adjust as ncessary.

Below is a screenshot of the search result:

![image](https://cloud.githubusercontent.com/assets/26195580/24380622/309cf57c-1301-11e7-9923-fe385315f097.png)

**Comment by atom0s** [comment]
This will need to be reported to @R3P0FFXI and/or @TeoTwawki to fix in the database. This is not a bug with the website but an incorrect value in the drop table itself.

**Comment by TeoTwawki** [comment]
Its actually in dsp that way because they stupidly merge things without making sure its correct. Presumably some idiot thought this is how you get "1 to 2" of a drop, or copy pasted some garbage wiki shows, without checking what the results of doing this actually are.
```sql
INSERT INTO `mob_droplist` VALUES (3273,0,0,1000,3222,1760);
```
Since drops rates are rolled for *single items dropping 1 at a time* and are *0-1000* this "over 1000" value is just treated as if it were 1000 (or 100%).

R3's currently working on ignoring what DSP has and just redoing all of it. I'm currently working on a bunch of things, including a *correct* way to do the drops in DSP that even their mental midgets can comprehend. Wish me luck.
